apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.configServer.service.name}}
  labels:
    app: {{ .Values.configServer.name}}
spec:
  type: {{ .Values.configServer.service.type }}
  ports:
    - port: {{ .Values.configServer.service.port }}
      targetPort: cfs-port
      protocol: TCP
  selector:
    app: {{ .Values.configServer.name}}
